INSERT INTO movie (title, director, country_origin, description, genre, duration, poster_url) VALUES ('W deszczowy dzień w Nowym Jorku','Woody Allen','USA','Gdy dwoje młodych ludzi przyjeżdża na weekend do Nowego Jorku, miasto wita ich niepogodą i serią przygód.','Komedia',92,'https://fwcdn.pl/fpo/41/94/794194/7889452.6.jpg');
INSERT INTO movie (title, director, country_origin, description, genre, duration, poster_url) VALUES ('1917','Sam Mendes','Hiszpania Indie Kanada USA Wielka Brytania','Dwóch młodych żołnierzy - Schofield i Blake dostają rozkaz przedostania się za linie wroga, aby dostarczyć tajną wiadomość, która pozwoli brytyjskim żołnierzy uniknąć wpadnięcia w śmiertelną pułapkę.','Wojenny',119,'https://fwcdn.pl/fpo/69/80/816980/7913530.6.jpg');
INSERT INTO movie (title, director, country_origin, description, genre, duration, poster_url) VALUES ('Joker','Todd Phillips','Kanada USA','Strudzony życiem komik popada w obłęd i staje się psychopatycznym mordercą.','Dramat / Kryminał',122,'https://fwcdn.pl/fpo/01/67/810167/7905225.6.jpg');
INSERT INTO movie (title, director, country_origin, description, genre, duration, poster_url) VALUES ('Saint Maud','Rose Glass','Wielka Brytania','Maud przyjeżdża do luksusowej posiadłości ekscentrycznej Amandy. Wkrótce dziewczyna przekonuje się o swojej ważnej misji, która zamieni się w niebezpieczną obsesję...','Horror',83,'https://fwcdn.pl/fpo/09/45/840945/7933376.6.jpg');
INSERT INTO movie (title, director, country_origin, description, genre, duration, poster_url) VALUES ('Irlandczyk','Martin Scorsese','USA','Płatny zabójca Frank Sheeran powraca do sekretów, których strzegł jako lojalny członek rodziny przestępczej Bufalino.','Biograficzny / Gangsterski',210,'https://fwcdn.pl/fpo/37/94/513794/7902504.6.jpg');
INSERT INTO cinema (city, street) VALUES ('Gliwice','Kopernika 75');
INSERT INTO auditorium (cinema_id) VALUES (1);
INSERT INTO seat (row,number,auditorium_id) VALUES (1,1,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (1,2,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (1,3,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (1,4,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (1,5,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (1,6,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (1,7,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (1,8,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (1,9,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (1,10,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (2,1,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (2,2,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (2,3,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (2,4,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (2,5,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (2,6,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (2,7,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (2,8,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (2,9,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (2,10,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (3,1,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (3,2,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (3,3,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (3,4,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (3,5,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (3,6,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (3,7,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (3,8,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (3,9,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (3,10,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (4,1,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (4,2,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (4,3,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (4,4,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (4,5,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (4,6,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (4,7,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (4,8,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (4,9,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (4,10,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (5,1,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (5,2,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (5,3,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (5,4,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (5,5,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (5,6,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (5,7,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (5,8,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (5,9,1);
INSERT INTO seat (row,number,auditorium_id) VALUES (5,10,1);
