INSERT INTO movie (title, director, country_origin, description, genre, duration, poster_url) VALUES ('W deszczowy dzień w Nowym Jorku','Woody Allen','USA','Gdy dwoje młodych ludzi przyjeżdża na weekend do Nowego Jorku, miasto wita ich niepogodą i serią przygód.','Komedia',92,'https://fwcdn.pl/fpo/41/94/794194/7889452.6.jpg');
INSERT INTO movie (title, director, country_origin, description, genre, duration, poster_url) VALUES ('1917','Sam Mendes','Hiszpania Indie Kanada USA Wielka Brytania','Dwóch młodych żołnierzy - Schofield i Blake dostają rozkaz przedostania się za linie wroga, aby dostarczyć tajną wiadomość, która pozwoli brytyjskim żołnierzy uniknąć wpadnięcia w śmiertelną pułapkę.','Wojenny',119,'https://fwcdn.pl/fpo/69/80/816980/7913530.6.jpg');
INSERT INTO movie (title, director, country_origin, description, genre, duration, poster_url) VALUES ('Joker','Todd Phillips','Kanada USA','Strudzony życiem komik popada w obłęd i staje się psychopatycznym mordercą.','Dramat / Kryminał',122,'https://fwcdn.pl/fpo/01/67/810167/7905225.6.jpg');
INSERT INTO movie (title, director, country_origin, description, genre, duration, poster_url) VALUES ('Saint Maud','Rose Glass','Wielka Brytania','Maud przyjeżdża do luksusowej posiadłości ekscentrycznej Amandy. Wkrótce dziewczyna przekonuje się o swojej ważnej misji, która zamieni się w niebezpieczną obsesję...','Horror',83,'https://fwcdn.pl/fpo/09/45/840945/7933376.6.jpg');
INSERT INTO movie (title, director, country_origin, description, genre, duration, poster_url) VALUES ('Irlandczyk','Martin Scorsese','USA','Płatny zabójca Frank Sheeran powraca do sekretów, których strzegł jako lojalny członek rodziny przestępczej Bufalino.','Biograficzny / Gangsterski',210,'https://fwcdn.pl/fpo/37/94/513794/7902504.6.jpg');
INSERT INTO movie (title, director, country_origin, description, genre, duration, poster_url) VALUES ('365 dni','Barbara Białowąs / Tomasz Mandes','Polska','Laura, aby ratować rozpadający się związek, wyjeżdża na Sycylię, gdzie poznaje Massimo. Niebezpieczny mężczyzna, szef rodziny mafijnej, porywa ją i daje 365 dni na pokochanie go.','Erotyczny',116,'https://fwcdn.pl/fpo/24/52/842452/7909947.6.jpg');
INSERT INTO movie (title, director, country_origin, description, genre, duration, poster_url) VALUES ('Tenet','Christopher Nolan','Kanada USA Wielka Brytania','Uzbrojony tylko w jedno słowo — Tenet — bohater przenika w mroczny świat międzynarodowych szpiegów, próbując ocalić ludzkość. Do tego jednak nieodzowne okazuje się skorzystanie ze zjawiska wykraczającego poza czas realny.','Thriller / Akcja / Sci-Fi',150,'https://fwcdn.pl/fpo/16/53/831653/7926046.6.jpg');
INSERT INTO movie (title, director, country_origin, description, genre, duration, poster_url) VALUES ('Sala samobójców. Hejter','Jan Komasa','Polska','Wydalony z Uniwersytetu Warszawskiego student prawa, zostaje przyłapany na plagiacie. Postanawia jednak ukrywać ten fakt przed światem i nadal pobiera pomoc finansową od państwa Krasuckich.','Thriller',130,'https://fwcdn.pl/fpo/80/17/818017/7914782.6.jpg');
INSERT INTO movie (title, director, country_origin, description, genre, duration, poster_url) VALUES ('Mulan','Niki Caro','USA','Kobieta o imieniu Hua Mulan przebrana za mężczyznę zaciąga się do cesarskiej armii, aby pomóc swojemu schorowanemu ojcu.','Fantasy / Przygodowy',115,'https://fwcdn.pl/fpo/00/66/740066/7929880.6.jpg');
INSERT INTO movie (title, director, country_origin, description, genre, duration, poster_url) VALUES ('Psy 3. W imię zasad','Władysław Pasikowski','Polska','Po 25 latach odsiadki Franz Maurer wkracza w nową Polskę, gdzie nic nie jest takie, jak zapamiętał. Wkrótce ponownie spotyka Nowego.','Sensacyjny',126,'https://fwcdn.pl/fpo/58/16/835816/7908750.6.jpg');
INSERT INTO movie (title, director, country_origin, description, genre, duration, poster_url) VALUES ('25 lat niewinności. Sprawa Tomka Komendy','Jan Holoubek','Polska','Tomasz Komenda miał 23 lata, kiedy jego normalne życie zostało brutalnie przerwane. Z dnia na dzień został zatrzymany...','Dramat / Sensacyjny',116,'https://fwcdn.pl/fpo/43/42/844342/7930471.6.jpg');
INSERT INTO movie (title, director, country_origin, description, genre, duration, poster_url) VALUES ('Naprzód','Dan Scanlon','21 lutego 2020 (świat)','Dwóch braci próbuje sprowadzić na ziemię drugą połowę ciała swojego ojca, gdyż nieudane czary powodują, że pojawia się tylko od pasa w dół.','Animacja',102,'https://fwcdn.pl/fpo/21/78/832178/7890671.6.jpg');
INSERT INTO movie (title, director, country_origin, description, genre, duration, poster_url) VALUES ('Proces Siódemki z Chicago','Aaron Sorkin','USA','Pokojowy protest przerodził się w brutalne starcie z policją, a jego organizatorzy stanęli przed sądem. Tak rozpoczął się jeden z najgłośniejszych procesów w historii.','Dramat sądowy',129,'https://fwcdn.pl/fpo/12/41/451241/7931788.6.jpg');
INSERT INTO movie (title, director, country_origin, description, genre, duration, poster_url) VALUES ('Zenek','Jan Hryniak','Polska','Historia chłopaka z podlaskiej wsi, który realizuje swoje wielkie marzenie, by śpiewać i bawić tłumy. Dzięki uporowi, ciężkiej pracy i wielu wyrzeczeniom osiągnął niebywały sukces.','Biograficzny / Muzyczny',120,'https://fwcdn.pl/fpo/92/25/829225/7911651.6.jpg');
INSERT INTO movie (title, director, country_origin, description, genre, duration, poster_url) VALUES ('Dylemat społeczny','Jeff Orlowski','USA','Ukazanie groźnych skutków ludzkiego wpływu na sieci społecznościowe. Ten problem najlepiej zauważają ich twórcy — eksperci ds. technologii.','Dokumentalny',89,'https://fwcdn.pl/fpo/95/86/859586/7930217.6.jpg');
INSERT INTO movie (title, director, country_origin, description, genre, duration, poster_url) VALUES ('Na rauszu','Thomas Vinterberg','Dania','"Na rauszu" opowiada historię grupy przyjaciół, nauczycieli szkoły średniej, zainspirowanych teorią, że skromna dawka alkoholu pozwala otworzyć się na świat i lepiej w nim funkcjonować.','Dramat / Komedia',115,'https://fwcdn.pl/fpo/88/72/838872/7935240.6.jpg');
INSERT INTO movie (title, director, country_origin, description, genre, duration, poster_url) VALUES ('Pewnego razu... w Hollywood','Quentin Tarantino','USA Wielka Brytania','Aktor Rick Dalton i jego przyjaciel kaskader powracają do Hollywood. Mężczyźni próbują odnaleźć się w przemyśle filmowym, który ewoluował podczas ich nieobecności.','Dramat / Kryminał',161,'https://fwcdn.pl/fpo/45/61/804561/7891889.6.jpg');
INSERT INTO movie (title, director, country_origin, description, genre, duration, poster_url) VALUES ('Parasite','Joon-ho Bong','Korea Południowa','Kiedy Ki-woo dostaje pracę jako korepetytor córki zamożnego małżeństwa, wymyśla sposób na zapewnienie zatrudnienia również reszcie swojej rodziny.','Dramat',132,'https://fwcdn.pl/fpo/81/43/798143/7895390.6.jpg');
INSERT INTO movie (title, director, country_origin, description, genre, duration, poster_url) VALUES ('Green Book','Peter Farrelly','USA','Drobny cwaniaczek z Bronksu zostaje szoferem ekstrawaganckiego muzyka z wyższych sfer i razem wyruszają na wielotygodniowe tournée.','Dramat / Komedia',130,'https://fwcdn.pl/fpo/96/30/809630/7873350.6.jpg');
INSERT INTO movie (title, director, country_origin, description, genre, duration, poster_url) VALUES ('Bohemian Rhapsody','Bryan Singer','USA Wielka Brytania','Dzięki oryginalnemu brzmieniu Queen staje się jednym z najpopularniejszych zespołów w historii muzyki.','Biograficzny / Dramat / Muzyczny',134,'https://fwcdn.pl/fpo/92/01/619201/7863181.6.jpg');
INSERT INTO cinema (city, street) VALUES ('Gliwice','Zwycięstwa 1');
INSERT INTO auditorium (cinema_id, seat_row_count, seat_number_count,screen_start,screen_end) VALUES (1,5,10,2,9);
INSERT INTO cinema (city, street) VALUES ('Warszawa','Wiejska 4/6/8');
INSERT INTO auditorium (cinema_id, seat_row_count, seat_number_count,screen_start,screen_end) VALUES (2,7,15,2,14);
INSERT INTO auditorium (cinema_id, seat_row_count, seat_number_count,screen_start,screen_end) VALUES (2,4,16,2,14);

INSERT INTO auditorium (cinema_id, seat_row_count, seat_number_count,screen_start,screen_end) VALUES (1,4,15,2,14);
INSERT INTO screening (auditorium_id, movie_id, screening_date, screening_time) VALUES (1, 17, CURDATE(),'10:15:00');
INSERT INTO screening (auditorium_id, movie_id, screening_date, screening_time) VALUES (2, 17, CURDATE(),'10:15:00');
INSERT INTO screening (auditorium_id, movie_id, screening_date, screening_time) VALUES (4, 17, CURDATE(),'10:15:00');
INSERT INTO screening (auditorium_id, movie_id, screening_date, screening_time) VALUES (1, 20, CURDATE(),'13:20:00');
INSERT INTO screening (auditorium_id, movie_id, screening_date, screening_time) VALUES (2, 20, CURDATE(),'13:20:00');
INSERT INTO screening (auditorium_id, movie_id, screening_date, screening_time) VALUES (4, 20, CURDATE(),'13:20:00');
INSERT INTO screening (auditorium_id, movie_id, screening_date, screening_time) VALUES (1, 18, CURDATE(),'17:00:00');
INSERT INTO screening (auditorium_id, movie_id, screening_date, screening_time) VALUES (2, 18, CURDATE(),'17:00:00');
INSERT INTO screening (auditorium_id, movie_id, screening_date, screening_time) VALUES (4, 18, CURDATE(),'17:00:00');
INSERT INTO screening (auditorium_id, movie_id, screening_date, screening_time) VALUES (1, 10, CURDATE(),'20:45:00');
INSERT INTO screening (auditorium_id, movie_id, screening_date, screening_time) VALUES (2, 10, CURDATE(),'21:45:00');
INSERT INTO screening (auditorium_id, movie_id, screening_date, screening_time) VALUES (4, 10, CURDATE(),'23:45:00');
INSERT INTO screening (auditorium_id, movie_id, screening_date, screening_time) VALUES (1, 17, DATE_ADD(CURDATE(),INTERVAL 1 DAY),'15:00:00');
INSERT INTO screening (auditorium_id, movie_id, screening_date, screening_time) VALUES (1, 17, DATE_ADD(CURDATE(),INTERVAL 1 DAY),'10:15:00');
INSERT INTO screening (auditorium_id, movie_id, screening_date, screening_time) VALUES (2, 17, DATE_ADD(CURDATE(),INTERVAL 1 DAY),'10:15:00');
INSERT INTO screening (auditorium_id, movie_id, screening_date, screening_time) VALUES (4, 17, DATE_ADD(CURDATE(),INTERVAL 1 DAY),'10:15:00');
INSERT INTO screening (auditorium_id, movie_id, screening_date, screening_time) VALUES (1, 20, DATE_ADD(CURDATE(),INTERVAL 1 DAY),'13:20:00');
INSERT INTO screening (auditorium_id, movie_id, screening_date, screening_time) VALUES (2, 20, DATE_ADD(CURDATE(),INTERVAL 1 DAY),'13:20:00');
INSERT INTO screening (auditorium_id, movie_id, screening_date, screening_time) VALUES (4, 20, DATE_ADD(CURDATE(),INTERVAL 1 DAY),'13:20:00');
INSERT INTO screening (auditorium_id, movie_id, screening_date, screening_time) VALUES (1, 18, DATE_ADD(CURDATE(),INTERVAL 1 DAY),'17:00:00');
INSERT INTO screening (auditorium_id, movie_id, screening_date, screening_time) VALUES (2, 18, DATE_ADD(CURDATE(),INTERVAL 1 DAY),'17:00:00');
INSERT INTO screening (auditorium_id, movie_id, screening_date, screening_time) VALUES (4, 18, DATE_ADD(CURDATE(),INTERVAL 1 DAY),'17:00:00');
INSERT INTO screening (auditorium_id, movie_id, screening_date, screening_time) VALUES (1, 10, DATE_ADD(CURDATE(),INTERVAL 1 DAY),'19:45:00');
INSERT INTO screening (auditorium_id, movie_id, screening_date, screening_time) VALUES (2, 10, DATE_ADD(CURDATE(),INTERVAL 1 DAY),'19:45:00');
INSERT INTO screening (auditorium_id, movie_id, screening_date, screening_time) VALUES (4, 10, DATE_ADD(CURDATE(),INTERVAL 1 DAY),'19:45:00');
INSERT INTO reservation (email, reserved_seat_number, user_name, user_surname, screening_id) VALUES ('adikmor@o2.pl',3,'Adam','Morytko',10);
INSERT INTO reserved_seat (number, row, reservation_id,screening_id) VALUES (5,4,1,10);
INSERT INTO reserved_seat (number, row, reservation_id,screening_id) VALUES (6,4,1,10);
INSERT INTO reserved_seat (number, row, reservation_id,screening_id) VALUES (7,4,1,10);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,1,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,2,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,3,1,2);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,4,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,5,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,6,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,7,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,8,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,9,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,10,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,1,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,2,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,3,1,2);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,4,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,5,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,6,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,7,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,8,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,9,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,10,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,1,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,2,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,3,1,2);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,4,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,5,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,6,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,7,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,8,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,9,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,10,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,1,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,2,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,3,1,2);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,4,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,5,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,6,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,7,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,8,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,9,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,10,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (5,1,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (5,2,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (5,3,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (5,4,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (5,5,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (5,6,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (5,7,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (5,8,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (5,9,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (5,10,1,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,1,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,2,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,3,2,2);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,4,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,5,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,6,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,7,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,8,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,9,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,10,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,11,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,12,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,13,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,14,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,15,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,1,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,2,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,3,2,2);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,4,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,5,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,6,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,7,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,8,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,9,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,10,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,11,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,12,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,13,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,14,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,15,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,1,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,2,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,3,2,2);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,4,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,5,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,6,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,7,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,8,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,9,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,10,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,11,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,12,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,13,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,14,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,15,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,1,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,2,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,3,2,2);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,4,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,5,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,6,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,7,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,8,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,9,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,10,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,11,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,12,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,13,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,14,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,15,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (5,1,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (5,2,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (5,3,2,2);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (5,4,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (5,5,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (5,6,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (5,7,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (5,8,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (5,9,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (5,10,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (5,11,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (5,12,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (5,13,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (5,14,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (5,15,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (6,1,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (6,2,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (6,3,2,2);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (6,4,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (6,5,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (6,6,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (6,7,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (6,8,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (6,9,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (6,10,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (6,11,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (6,12,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (6,13,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (6,14,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (6,15,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (7,1,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (7,2,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (7,3,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (7,4,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (7,5,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (7,6,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (7,7,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (7,8,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (7,9,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (7,10,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (7,11,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (7,12,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (7,13,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (7,14,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (7,15,2,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,1,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,2,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,3,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,4,3,2);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,5,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,6,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,7,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,8,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,9,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,10,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,11,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,12,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,13,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,14,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,15,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,16,3,1);

INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,1,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,2,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,3,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,4,3,2);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,5,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,6,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,7,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,8,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,9,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,10,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,11,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,12,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,13,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,14,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,15,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,16,3,1);

INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,1,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,2,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,3,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,4,3,2);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,5,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,6,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,7,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,8,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,9,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,10,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,11,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,12,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,13,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,14,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,15,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,16,3,1);

INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,1,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,2,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,3,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,4,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,5,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,6,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,7,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,8,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,9,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,10,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,11,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,12,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,13,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,14,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,15,3,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,16,3,1);

INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,1,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,2,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,3,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,4,4,2);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,5,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,6,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,7,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,8,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,9,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,10,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,11,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,12,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,13,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,14,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (1,15,4,1);

INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,1,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,2,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,3,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,4,4,2);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,5,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,6,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,7,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,8,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,9,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,10,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,11,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,12,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,13,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,14,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (2,15,4,1);

INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,1,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,2,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,3,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,4,4,2);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,5,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,6,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,7,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,8,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,9,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,10,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,11,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,12,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,13,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,14,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (3,15,4,1);

INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,1,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,2,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,3,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,4,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,5,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,6,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,7,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,8,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,9,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,10,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,11,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,12,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,13,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,14,4,1);
INSERT INTO seat (row,number,auditorium_id,status) VALUES (4,15,4,1);
